### ISSUE TITLE
Can you provide a function script to build a .yaml configuration file based on a customized bvh file?

### ISSUE THREAD

**Issue by Lufffya** [facebookresearch/AnimatedDrawings#116] opened 2023-04-18 08:10 UTC
Because the existing retarget configuration file is not compatible with the customized bvh , 
manually building the retarget configuration file from the customized bvh is too unfriendly for beginners :broken_heart:

**Comment by hjessmith** [comment] 2023-04-18 19:07
Closing, duplicate of #101

**Closed by hjessmith** 2023-04-18 19:07 UTC
